In [1]:
#Load processed images data into array
#SPLIT

import os
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


input_image_dir = "../processed_gear_images"

out_images_x = []
out_images_y = []
# Read all images from gear_images directory
for folder in sorted(os.listdir(input_image_dir)):
    folderpath = os.path.join(input_image_dir,folder)
    print(folderpath, ':')
    for file in sorted(os.listdir(folderpath)):
        in_file = folderpath + "/" + file
        out_images_x.append(in_file)
        out_images_y.append(folder)
#label encoding
le = preprocessing.LabelEncoder()
le.fit(out_images_y)
list(le.classes_)
out_images_y = le.transform(out_images_y) 
        
np_data_X = np.array([np.ravel(Image.open(fname)) for fname in out_images_x])
x_train, x_test, y_train, y_test = train_test_split(np_data_X, out_images_y, test_size=.2)


../processed_gear_images/axes :
../processed_gear_images/boots :
../processed_gear_images/carabiners :
../processed_gear_images/crampons :
../processed_gear_images/gloves :
../processed_gear_images/hardshell_jackets :
../processed_gear_images/harnesses :
../processed_gear_images/helmets :
../processed_gear_images/insulated_jackets :
../processed_gear_images/pulleys :
../processed_gear_images/rope :
../processed_gear_images/tents :


In [5]:
print(y_train)
print(y_train.shape)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(1697, 12)


In [6]:
# CNN basic

from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os

batch_size = 32
num_classes = 12
epochs = 10
data_augmentation = True
num_predictions = 20
save_dir = "../processed_gear_images"
model_name = 'keras_team6_cnn_trained_model.h5'

# The data, split between train and test sets:
#(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=(128, 128, 3)))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

x_train shape: (1697, 49152)
1697 train samples
425 test samples
